#!/usr/bin/env python
# coding=utf-8
"""Negative-prompt CFG distillation (Meng et al. style w-conditioned student) for SD1.4.

Teacher target (per sample):
    eps_pos = ref_unet(x_t, t, c)           # positive prompt
    eps_neg = ref_unet(x_t, t, c-)          # random-removal negative prompt
    eps_CFG_neg = eps_neg + s * (eps_pos - eps_neg)
                = eps_pos + lambda * (eps_pos - eps_neg)   with s = 1 + lambda

Student loss:
    L = || student_unet(x_t, t, c; w) - sg[eps_CFG_neg] ||^2

Student is w-conditioned: the SD1.4 UNet is rebuilt with `time_cond_proj_dim`
so that an additional sinusoidal embedding of the guidance scale `s` is added
to the time embedding (the same trick used in LCM-LoRA training).

Positive image latents come from a pre-encoded latent dataset
(e.g. data/latents/diffusiondb_llama_200k); negative prompts come from the
`neg_prompt` / `all_neg_prompts` fields of the same metadata
(generated by prompts_generation/DiffusionDB_random_removal.py).
"""

import argparse
import logging
import math
import os
import random
import shutil
from pathlib import Path

import accelerate
import datasets
import numpy as np
import torch
import torch.nn.functional as F
import torch.utils.checkpoint
import transformers
from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.state import AcceleratorState
from accelerate.utils import ProjectConfiguration, set_seed
from packaging import version
from torch.utils.data import Subset
from tqdm.auto import tqdm
from transformers import CLIPTextModel, CLIPTokenizer
from transformers.utils import ContextManagers

import diffusers
from diffusers import (
    AutoencoderKL,
    DDPMScheduler,
    StableDiffusionPipeline,
    UNet2DConditionModel,
)
from diffusers.optimization import get_scheduler
from diffusers.utils import check_min_version, is_wandb_available
from diffusers.utils.import_utils import is_xformers_available

from dataset import collate_fn, self_training_dataset

if is_wandb_available():
    import wandb


check_min_version("0.20.0")

logger = get_logger(__name__, log_level="INFO")


# ---------------------------------------------------------------------------
# Guidance-scale embedding (LCM / Meng et al. style)
# ---------------------------------------------------------------------------
def guidance_scale_embedding(w, embedding_dim=256, dtype=torch.float32):
    """Sinusoidal embedding of a guidance scale `w`.

    Computed in fp32 internally (sin/cos of values up to ~7000 is unsafe in
    fp16) and cast to `dtype` only at the end. Matches diffusers' LCM helper.
    Input  : w of shape (B,) — guidance scale per sample.
    Output : (B, embedding_dim) in `dtype`.
    """
    assert w.ndim == 1
    w_fp32 = w.float() * 1000.0
    half_dim = embedding_dim // 2
    freq = math.log(10000.0) / (half_dim - 1)
    freq = torch.exp(torch.arange(half_dim, dtype=torch.float32, device=w.device) * -freq)
    emb = w_fp32[:, None] * freq[None, :]
    emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=1)
    if embedding_dim % 2 == 1:
        emb = F.pad(emb, (0, 1))
    return emb.to(dtype)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser()
    # Model / data
    parser.add_argument("--pretrained_model_name_or_path", type=str, required=True,
                        help="SD1.4-style model id or local path.")
    parser.add_argument("--revision", type=str, default=None)
    parser.add_argument("--train_data_dir", type=str, required=True,
                        help="Pre-encoded latent dir with metadata.jsonl + latents/.")
    parser.add_argument("--cache_dir", type=str, default=None)
    parser.add_argument("--output_dir", type=str, default="cfg-distill-neg")
    parser.add_argument("--logging_dir", type=str, default="logs")
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--max_train_samples", type=int, default=None)

    # Student w-conditioning
    parser.add_argument("--time_cond_proj_dim", type=int, default=256,
                        help="Dim of the guidance-scale embedding fed into time_embedding.cond_proj.")
    parser.add_argument("--guidance_min", type=float, default=2.0,
                        help="Lower bound for U[s_min, s_max] guidance-scale sampling.")
    parser.add_argument("--guidance_max", type=float, default=8.0,
                        help="Upper bound for U[s_min, s_max] guidance-scale sampling.")

    # Optim
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--train_batch_size", type=int, default=8)
    parser.add_argument("--num_train_epochs", type=int, default=100)
    parser.add_argument("--max_train_steps", type=int, default=2000)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--gradient_checkpointing", action="store_true")
    parser.add_argument("--learning_rate", type=float, default=1e-6)
    parser.add_argument("--scale_lr", action="store_true")
    parser.add_argument("--lr_scheduler", type=str, default="constant_with_warmup")
    parser.add_argument("--lr_warmup_steps", type=int, default=500)
    parser.add_argument("--use_adafactor", action="store_true")
    parser.add_argument("--allow_tf32", action="store_true")
    parser.add_argument("--dataloader_num_workers", type=int, default=0)
    parser.add_argument("--adam_beta1", type=float, default=0.9)
    parser.add_argument("--adam_beta2", type=float, default=0.999)
    parser.add_argument("--adam_weight_decay", type=float, default=1e-2)
    parser.add_argument("--adam_epsilon", type=float, default=1e-08)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)

    # Misc
    parser.add_argument("--mixed_precision", type=str, default="fp16",
                        choices=["no", "fp16", "bf16"])
    parser.add_argument("--report_to", type=str, default="tensorboard")
    parser.add_argument("--tracker_project_name", type=str, default="cfg-distill-neg")
    parser.add_argument("--checkpointing_steps", type=int, default=500)
    parser.add_argument("--resume_from_checkpoint", type=str, default="latest")
    parser.add_argument("--hard_skip_resume", action="store_true")
    parser.add_argument("--noise_offset", type=float, default=0.0)
    parser.add_argument("--input_perturbation", type=float, default=0.0)
    parser.add_argument("--timestep_sampling", type=str, default=None,
                        help="None / 'linear' / 'sigmoid' (forwarded to dataset).")

    args = parser.parse_args()
    if args.guidance_min > args.guidance_max:
        raise ValueError("--guidance_min must be <= --guidance_max")
    return args


def sanitize_tracker_config(config_dict):
    safe_config = {}
    for k, v in config_dict.items():
        if isinstance(v, (int, float, str, bool, torch.Tensor)):
            safe_config[k] = v
        elif isinstance(v, list) and all(isinstance(item, str) for item in v):
            safe_config[k] = ",".join(v)
    return safe_config


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    args = parse_args()

    logging_dir = os.path.join(args.output_dir, args.logging_dir)
    accelerator_project_config = ProjectConfiguration(project_dir=args.output_dir, logging_dir=logging_dir)
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
        project_config=accelerator_project_config,
    )

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logger.info(accelerator.state, main_process_only=False)
    if accelerator.is_local_main_process:
        datasets.utils.logging.set_verbosity_warning()
        transformers.utils.logging.set_verbosity_warning()
        diffusers.utils.logging.set_verbosity_info()
    else:
        datasets.utils.logging.set_verbosity_error()
        transformers.utils.logging.set_verbosity_error()
        diffusers.utils.logging.set_verbosity_error()

    if args.seed is not None:
        set_seed(args.seed + accelerator.process_index)

    if accelerator.is_main_process:
        os.makedirs(args.output_dir, exist_ok=True)

    # -----------------------------------------------------------------------
    # Models
    # -----------------------------------------------------------------------
    noise_scheduler = DDPMScheduler.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="scheduler", cache_dir=args.cache_dir
    )
    tokenizer = CLIPTokenizer.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="tokenizer", revision=args.revision, cache_dir=args.cache_dir
    )

    def deepspeed_zero_init_disabled_context_manager():
        deepspeed_plugin = AcceleratorState().deepspeed_plugin if accelerate.state.is_initialized() else None
        if deepspeed_plugin is None:
            return []
        return [deepspeed_plugin.zero3_init_context_manager(enable=False)]

    with ContextManagers(deepspeed_zero_init_disabled_context_manager()):
        text_encoder = CLIPTextModel.from_pretrained(
            args.pretrained_model_name_or_path, subfolder="text_encoder",
            revision=args.revision, cache_dir=args.cache_dir,
        )
        vae = AutoencoderKL.from_pretrained(
            args.pretrained_model_name_or_path, subfolder="vae",
            revision=args.revision, cache_dir=args.cache_dir,
        )
        # Frozen teacher (no time_cond_proj_dim — vanilla SD1.4 UNet).
        ref_unet = UNet2DConditionModel.from_pretrained(
            args.pretrained_model_name_or_path, subfolder="unet",
            revision=args.revision, cache_dir=args.cache_dir,
        )
        # Student = same weights + extra cond_proj layer for guidance-scale embedding.
        unet = UNet2DConditionModel.from_pretrained(
            args.pretrained_model_name_or_path, subfolder="unet",
            revision=args.revision, cache_dir=args.cache_dir,
            time_cond_proj_dim=args.time_cond_proj_dim,
            low_cpu_mem_usage=False,
            ignore_mismatched_sizes=True,
        )

    # Zero-init the newly-added cond_proj. With Kaiming-init the student
    # immediately disagrees with the teacher (cond_proj(w_emb) injects ~O(1)
    # random perturbation into the time embedding), and the s≤8 amplification
    # in the CFG target then explodes gradients -> NaN within a few hundred
    # steps. Zeroing cond_proj makes step-0 behavior identical to the teacher,
    # standard practice when adding new conditioning to a pretrained model
    # (ControlNet / IP-Adapter / LCM all do this).
    if hasattr(unet.time_embedding, "cond_proj") and unet.time_embedding.cond_proj is not None:
        torch.nn.init.zeros_(unet.time_embedding.cond_proj.weight)

    vae.requires_grad_(False)
    text_encoder.requires_grad_(False)
    ref_unet.requires_grad_(False)

    if is_xformers_available():
        try:
            unet.enable_xformers_memory_efficient_attention()
            ref_unet.enable_xformers_memory_efficient_attention()
        except Exception as e:
            # xformers ships pre-compiled kernels for limited GPU caps. On newer
            # GPUs (e.g. Blackwell sm_120) the dispatch sanity check fails — fall
            # back to PyTorch's native SDPA, which diffusers uses by default.
            logger.warning(f"xformers unavailable on this GPU; using SDPA. ({e})")

    if version.parse(accelerate.__version__) >= version.parse("0.16.0"):
        def save_model_hook(models, weights, output_dir):
            for model in models[:1]:
                model.save_pretrained(os.path.join(output_dir, "unet"))
                weights.pop()

        def load_model_hook(models, input_dir):
            model = models.pop()
            load_model = UNet2DConditionModel.from_pretrained(input_dir, subfolder="unet")
            model.register_to_config(**load_model.config)
            model.load_state_dict(load_model.state_dict())
            del load_model

        accelerator.register_save_state_pre_hook(save_model_hook)
        accelerator.register_load_state_pre_hook(load_model_hook)

    if args.gradient_checkpointing:
        unet.enable_gradient_checkpointing()
    if args.allow_tf32:
        torch.backends.cuda.matmul.allow_tf32 = True
    if args.scale_lr:
        args.learning_rate = (
            args.learning_rate
            * args.gradient_accumulation_steps
            * args.train_batch_size
            * accelerator.num_processes
        )

    # Optim
    if args.use_adafactor:
        optimizer = transformers.Adafactor(
            unet.parameters(), lr=args.learning_rate,
            weight_decay=args.adam_weight_decay,
            clip_threshold=1.0, scale_parameter=False, relative_step=False,
        )
    else:
        optimizer = torch.optim.AdamW(
            unet.parameters(),
            lr=args.learning_rate,
            betas=(args.adam_beta1, args.adam_beta2),
            weight_decay=args.adam_weight_decay,
            eps=args.adam_epsilon,
        )

    # -----------------------------------------------------------------------
    # Dataset
    # -----------------------------------------------------------------------
    train_dataset = self_training_dataset(
        data_dir=args.train_data_dir,
        rand_cond=False,
        n_T=noise_scheduler.num_train_timesteps,
        timestep_sampling=args.timestep_sampling,
        random_neg_prompts=True,  # always sample from all_neg_prompts
    )
    if args.max_train_samples is not None:
        original_seed = random.getstate()
        random.seed(42)
        indices = random.sample(range(len(train_dataset)), args.max_train_samples)
        random.setstate(original_seed)
        train_dataset = Subset(train_dataset, indices)

    train_dataloader = torch.utils.data.DataLoader(
        train_dataset,
        shuffle=True,
        collate_fn=collate_fn(tokenizer),
        batch_size=args.train_batch_size,
        num_workers=args.dataloader_num_workers,
        drop_last=True,
    )

    # LR schedule
    overrode_max_train_steps = False
    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
    if args.max_train_steps is None:
        args.max_train_steps = args.num_train_epochs * num_update_steps_per_epoch
        overrode_max_train_steps = True

    lr_scheduler = get_scheduler(
        args.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps * accelerator.num_processes,
        num_training_steps=args.max_train_steps * accelerator.num_processes,
    )

    unet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        unet, optimizer, train_dataloader, lr_scheduler
    )

    weight_dtype = torch.float32
    if accelerator.mixed_precision == "fp16":
        weight_dtype = torch.float16
    elif accelerator.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16

    vae.to(accelerator.device, dtype=weight_dtype)
    text_encoder.to(accelerator.device, dtype=weight_dtype)
    ref_unet.to(accelerator.device, dtype=weight_dtype)

    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
    if overrode_max_train_steps:
        args.max_train_steps = args.num_train_epochs * num_update_steps_per_epoch
    args.num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)

    if accelerator.is_main_process:
        accelerator.init_trackers(args.tracker_project_name, sanitize_tracker_config(vars(args)))

    total_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
    logger.info("***** Running CFG-neg distillation *****")
    logger.info(f"  Num examples = {len(train_dataset)}")
    logger.info(f"  Num Epochs = {args.num_train_epochs}")
    logger.info(f"  Per-device batch = {args.train_batch_size}")
    logger.info(f"  Total train batch (w. grad accum & DDP) = {total_batch_size}")
    logger.info(f"  Total optim steps = {args.max_train_steps}")
    logger.info(f"  Guidance scale ~ U[{args.guidance_min}, {args.guidance_max}]  (s convention: eps_neg + s*(eps_pos - eps_neg))")

    global_step = 0
    first_epoch = 0
    resume_step = 0
    if args.resume_from_checkpoint:
        if args.resume_from_checkpoint != "latest":
            path = os.path.basename(args.resume_from_checkpoint)
        else:
            dirs = [d for d in os.listdir(args.output_dir) if d.startswith("checkpoint")] if os.path.isdir(args.output_dir) else []
            dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
            path = dirs[-1] if dirs else None
        if path is None:
            accelerator.print(f"Checkpoint '{args.resume_from_checkpoint}' not found — fresh run.")
            args.resume_from_checkpoint = None
        else:
            accelerator.print(f"Resuming from checkpoint {path}")
            accelerator.load_state(os.path.join(args.output_dir, path))
            global_step = int(path.split("-")[1])
            resume_global_step = global_step * args.gradient_accumulation_steps
            first_epoch = global_step // num_update_steps_per_epoch
            resume_step = resume_global_step % (num_update_steps_per_epoch * args.gradient_accumulation_steps)

    progress_bar = tqdm(range(global_step, args.max_train_steps), disable=not accelerator.is_local_main_process)
    progress_bar.set_description("Steps")

    # ---------------- training loop ----------------
    for epoch in range(first_epoch, args.num_train_epochs):
        unet.train()
        train_loss = 0.0
        for step, batch in enumerate(train_dataloader):
            if args.resume_from_checkpoint and epoch == first_epoch and step < resume_step and (not args.hard_skip_resume):
                if step % args.gradient_accumulation_steps == 0:
                    print(f"Dummy processing step {step}, will start training at {resume_step}")
                continue

            with accelerator.accumulate(unet):
                # batch["latents"]: (B, 2C, H, W) — pos and neg latents stacked along channel dim.
                # We only use the positive image latent for CFG-neg distillation.
                pos_latents, _neg_latents = batch["latents"].chunk(2, dim=1)
                latents = pos_latents.to(weight_dtype)

                bsz = latents.shape[0]
                noise = torch.randn_like(latents)
                if args.noise_offset:
                    noise = noise + args.noise_offset * torch.randn(
                        (bsz, latents.shape[1], 1, 1), device=latents.device, dtype=latents.dtype
                    )
                if args.input_perturbation:
                    perturbed_noise = noise + args.input_perturbation * torch.randn_like(noise)
                else:
                    perturbed_noise = noise

                timesteps = batch["timesteps"].long().to(latents.device)
                noisy_latents = noise_scheduler.add_noise(latents, perturbed_noise, timesteps)

                # Text encodings
                with torch.no_grad():
                    pos_embeds = text_encoder(batch["pos_input_ids"].to(latents.device))[0]
                    neg_embeds = text_encoder(batch["neg_input_ids"].to(latents.device))[0]

                # Sample guidance scales s ~ U[s_min, s_max] per example
                # `s` is the standard diffusers `guidance_scale` (s=1 -> no guidance).
                s = torch.empty(bsz, device=latents.device, dtype=torch.float32).uniform_(
                    args.guidance_min, args.guidance_max
                )

                # Teacher: two ref_unet forwards on the SAME positive noisy latent
                with torch.no_grad():
                    eps_pos = ref_unet(noisy_latents, timesteps, pos_embeds).sample
                    eps_neg = ref_unet(noisy_latents, timesteps, neg_embeds).sample
                    s_view = s.view(bsz, 1, 1, 1).to(eps_pos.dtype)
                    target = eps_neg + s_view * (eps_pos - eps_neg)

                # Student: w-conditioned via time_embedding.cond_proj.
                # Embed (s - 1) to match diffusers' SD pipeline convention
                # (`guidance_scale_tensor = guidance_scale - 1`); this lets you
                # later just do `pipe(..., guidance_scale=s)` without monkeying
                # with the pipeline.
                w_emb = guidance_scale_embedding(s - 1.0, embedding_dim=args.time_cond_proj_dim, dtype=weight_dtype)
                model_pred = unet(
                    noisy_latents, timesteps, pos_embeds,
                    timestep_cond=w_emb,
                ).sample

                loss = F.mse_loss(model_pred.float(), target.float(), reduction="mean")

                # Defensive NaN/Inf guard: if any rank produces non-finite
                # loss, zero the loss on that rank so the global gradient is
                # finite (still synchronised across DDP) and the optimizer
                # step is effectively a no-op for the bad rank. Without this a
                # single bad batch corrupts the model permanently.
                loss_is_finite = torch.isfinite(loss)
                if not loss_is_finite:
                    logger.warning(f"[step {global_step}] non-finite loss on rank {accelerator.process_index}; zeroing")
                    loss = loss * 0.0

                avg_loss = accelerator.gather(loss.repeat(args.train_batch_size)).mean()
                train_loss += avg_loss.item() / args.gradient_accumulation_steps

                accelerator.backward(loss)
                if accelerator.sync_gradients and not args.use_adafactor:
                    accelerator.clip_grad_norm_(unet.parameters(), args.max_grad_norm)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

            if accelerator.sync_gradients:
                progress_bar.update(1)
                global_step += 1
                accelerator.log({"train_loss": train_loss}, step=global_step)
                accelerator.log({"guidance_scale_mean": s.mean().item()}, step=global_step)
                train_loss = 0.0

                if global_step % args.checkpointing_steps == 0:
                    if accelerator.is_main_process:
                        save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")
                        accelerator.save_state(save_path)
                        logger.info(f"Saved state to {save_path}")

            progress_bar.set_postfix(step_loss=loss.detach().item(), lr=lr_scheduler.get_last_lr()[0],
                                     s=s.mean().item())

            if global_step >= args.max_train_steps:
                break

    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        unwrapped_unet = accelerator.unwrap_model(unet)
        pipeline = StableDiffusionPipeline.from_pretrained(
            args.pretrained_model_name_or_path,
            text_encoder=text_encoder,
            vae=vae,
            unet=unwrapped_unet,
            revision=args.revision,
            cache_dir=args.cache_dir,
        )
        pipeline.save_pretrained(args.output_dir)
    accelerator.end_training()


if __name__ == "__main__":
    main()
